// <auto-generated />
using System;
using DataManager.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataManager.Migrations
{
    [DbContext(typeof(CategoryContext))]
    [Migration("20250410182232_2322")]
    partial class _2322
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataManager.EF.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DataManager.EF.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<int?>("GoodsId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("GoodsId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("DataManager.EF.FieldDescribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<int>("GoodId")
                        .HasColumnType("integer");

                    b.Property<int?>("GoodsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("FieldId");

                    b.HasIndex("GoodsId");

                    b.ToTable("FieldDescribe");
                });

            modelBuilder.Entity("DataManager.EF.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Good");
                });

            modelBuilder.Entity("DataManager.EF.Field", b =>
                {
                    b.HasOne("DataManager.EF.Categories", null)
                        .WithMany("Fields")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManager.EF.Goods", null)
                        .WithMany("Fields")
                        .HasForeignKey("GoodsId");
                });

            modelBuilder.Entity("DataManager.EF.FieldDescribe", b =>
                {
                    b.HasOne("DataManager.EF.Categories", null)
                        .WithMany("FieldDescribes")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManager.EF.Field", null)
                        .WithMany("FieldDescribe")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManager.EF.Goods", null)
                        .WithMany("FieldDescribe")
                        .HasForeignKey("GoodsId");
                });

            modelBuilder.Entity("DataManager.EF.Goods", b =>
                {
                    b.HasOne("DataManager.EF.Categories", null)
                        .WithMany("Goods")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataManager.EF.Categories", b =>
                {
                    b.Navigation("FieldDescribes");

                    b.Navigation("Fields");

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("DataManager.EF.Field", b =>
                {
                    b.Navigation("FieldDescribe");
                });

            modelBuilder.Entity("DataManager.EF.Goods", b =>
                {
                    b.Navigation("FieldDescribe");

                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
